// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA0XjsGkYEmlYDoWNzXFdIKI9vict9P-sA',
    appId: '1:437855736878:web:918ddfcd7c61acf6723bbf',
    messagingSenderId: '437855736878',
    projectId: 'svendeproven-ee539',
    authDomain: 'svendeproven-ee539.firebaseapp.com',
    storageBucket: 'svendeproven-ee539.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYI_YfhMbMB6jZjbWOrAZOiHYYEVO1Szg',
    appId: '1:437855736878:android:906b52a5ba6c5ac4723bbf',
    messagingSenderId: '437855736878',
    projectId: 'svendeproven-ee539',
    storageBucket: 'svendeproven-ee539.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi7Rl1vlUL7gnrvRlWik79o9iwwbSyawM',
    appId: '1:437855736878:ios:f52ef13ed86de68a723bbf',
    messagingSenderId: '437855736878',
    projectId: 'svendeproven-ee539',
    storageBucket: 'svendeproven-ee539.appspot.com',
    iosClientId: '437855736878-9gcfjc35k7lpojh1mk5dqsolgs26q801.apps.googleusercontent.com',
    iosBundleId: 'dk.svendeproven',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi7Rl1vlUL7gnrvRlWik79o9iwwbSyawM',
    appId: '1:437855736878:ios:6b2584b9bed20912723bbf',
    messagingSenderId: '437855736878',
    projectId: 'svendeproven-ee539',
    storageBucket: 'svendeproven-ee539.appspot.com',
    iosClientId: '437855736878-vtc917vjl5f89rnm86q3vqsaq3qlcr1p.apps.googleusercontent.com',
    iosBundleId: 'com.example.examApp',
  );
}
